policy:
  cherry-pick:
    upstream:
      - github: systemd/systemd
      - github: systemd/systemd-stable
    exception:
      note:
        # Exception for RHEL-only commits that should be kept in case of rebase
        - rhel-only
        # Exception for commits that cannot be cherry-picked due to conflicts but are based on upstream commits
        - based-on-upstream
  tracker:
    - keyword:
        - 'Resolves: #?'
        - 'Related: #?'
        - 'Reverts: #?'
      issue-format:
        - '\d+$'
      url: 'https://bugzilla.redhat.com/show_bug.cgi?id='
    - keyword:
        - 'Resolves: '
        - 'Related: '
        - 'Reverts: '
      issue-format:
        - 'RHEL-\d+$'
      url: 'https://issues.redhat.com/browse/'
