---
# vi: ts=2 sw=2 et:
#
name: Unit tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CENTOS_RELEASE: "centos8"
      CONT_NAME:      "systemd-centos8-ci"
    strategy:
      fail-fast: false
      matrix:
        run_phase: [GCC, GCC_ASAN]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - name: Install build dependencies
        run: sudo -E .github/workflows/unit_tests.sh SETUP
      - name: Build & test (${{ matrix.run_phase }})
        run: sudo -E .github/workflows/unit_tests.sh RUN_${{ matrix.run_phase }}
      - name: Cleanup
        run: sudo -E .github/workflows/unit_tests.sh CLEANUP
