---
# vi: ts=2 sw=2 et:
#
name: Unit tests
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        run_phase: [GCC, GCC_ASAN]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - name: Install build dependencies
        run: sudo -E .github/workflows/unit_tests.sh SETUP
      - name: Build & test (${{ matrix.run_phase }})
        run: sudo -E .github/workflows/unit_tests.sh RUN_${{ matrix.run_phase }}
      - name: Cleanup
        run: sudo -E .github/workflows/unit_tests.sh CLEANUP
