---
# vi: ts=2 sw=2 et:
#
name: Unit tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image: [stream8]
        phase: [GCC, GCC_ASAN]
    env:
      CONT_NAME: "systemd-centos8-ci"
      CENTOS_RELEASE: ${{ matrix.image }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - name: Install build dependencies
        run: sudo -E .github/workflows/unit_tests.sh SETUP
      - name: Build & test (${{ env.CENTOS_RELEASE }} / ${{ matrix.phase }})
        run: |
          set -x
          echo "Before test"
          sudo -E .github/workflows/unit_tests.sh RUN_${{ matrix.phase }} || exit 1
          echo "After test: $?"

      - name: Cleanup
        run: sudo -E .github/workflows/unit_tests.sh CLEANUP
